# Generated by Django 3.2.25 on 2026-07-12 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('points_per_question', models.IntegerField(default=10, verbose_name='每题分值')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'db_table': 'learning_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('category', models.CharField(db_index=True, max_length=100, verbose_name='分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_points', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
                'db_table': 'learning_knowledge_points',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='题目内容')),
                ('option_a', models.CharField(max_length=500, verbose_name='选项A')),
                ('option_b', models.CharField(max_length=500, verbose_name='选项B')),
                ('option_c', models.CharField(max_length=500, verbose_name='选项C')),
                ('option_d', models.CharField(max_length=500, verbose_name='选项D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='正确答案')),
                ('difficulty', models.IntegerField(default=3, verbose_name='难度(1-5)')),
                ('explanation', models.TextField(blank=True, verbose_name='答案解析')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.knowledgepoint', verbose_name='知识点')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'learning_questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmittedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('correct_count', models.IntegerField(default=0, verbose_name='正确题数')),
                ('total_count', models.IntegerField(default=0, verbose_name='总题数')),
                ('is_late', models.BooleanField(default=False, verbose_name='是否迟交')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning.assignment', verbose_name='作业')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '提交的作业',
                'verbose_name_plural': '提交的作业',
                'db_table': 'learning_submitted_assignments',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='SubmittedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=1, verbose_name='选择的答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.question', verbose_name='题目')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.submittedassignment', verbose_name='提交记录')),
            ],
            options={
                'verbose_name': '提交的答案',
                'verbose_name_plural': '提交的答案',
                'db_table': 'learning_submitted_answers',
            },
        ),
        migrations.CreateModel(
            name='StudentPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='总积分')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_record', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生积分',
                'verbose_name_plural': '学生积分',
                'db_table': 'learning_student_points',
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='顺序')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.assignment', verbose_name='作业')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '作业题目',
                'verbose_name_plural': '作业题目',
                'db_table': 'learning_assignment_questions',
                'ordering': ['order'],
                'unique_together': {('assignment', 'question')},
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='questions',
            field=models.ManyToManyField(through='learning.AssignmentQuestion', to='learning.Question', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='教师'),
        ),
    ]
