# Generated by Django 3.2.25 on 2026-07-13 20:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课程名称')),
                ('description', models.TextField(verbose_name='课程描述')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='course_covers/', verbose_name='封面图片')),
                ('difficulty', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级')], default='beginner', max_length=20, verbose_name='难度')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name='授课教师')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('content', models.TextField(verbose_name='章节内容')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='视频链接')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='章节顺序')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='预计学习时长(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作业标题')),
                ('description', models.TextField(verbose_name='作业描述')),
                ('question', models.TextField(verbose_name='题目要求')),
                ('starter_code', models.TextField(blank=True, null=True, verbose_name='初始代码')),
                ('test_cases', models.JSONField(blank=True, default=list, verbose_name='测试用例')),
                ('max_score', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='满分')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='easy', max_length=20, verbose_name='难度')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='learning.lesson', verbose_name='所属章节')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'ordering': ['lesson', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='提交代码')),
                ('score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='得分')),
                ('status', models.CharField(choices=[('pending', '待批改'), ('passed', '通过'), ('failed', '未通过'), ('grading', '批改中')], default='pending', max_length=20, verbose_name='状态')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='教师反馈')),
                ('test_result', models.JSONField(blank=True, default=dict, verbose_name='测试结果')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='批改时间')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning.assignment', verbose_name='作业')),
                ('student', models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '作业提交',
                'verbose_name_plural': '作业提交',
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='最后访问时间')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='学习时长(分钟)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.lesson', verbose_name='章节')),
                ('student', models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '学习进度',
                'verbose_name_plural': '学习进度',
                'ordering': ['-last_accessed'],
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='选课时间')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.course', verbose_name='课程')),
                ('student', models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '选课记录',
                'verbose_name_plural': '选课记录',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
