# Generated by Django 3.2.25 on 2026-07-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='邮箱')),
                ('id_num', models.CharField(max_length=20, unique=True, verbose_name='学号/工号')),
                ('username', models.CharField(max_length=16, verbose_name='姓名')),
                ('school', models.CharField(blank=True, max_length=50, null=True, verbose_name='学校')),
                ('school_short', models.CharField(blank=True, max_length=10, null=True, verbose_name='学校缩写')),
                ('allow_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='允许创建数')),
                ('create_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='剩余可创建数')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'myauth_myuser',
            },
        ),
    ]
